# FROM is used to mention the base OS of the image. It should be the first instruction in Dockerfile.
# Almalinux is exactly same as Redhat Image version 9
# LABEL is used to add the metadata to the image, It is also used for filtration when large number of images are present in container.
FROM almalinux:9
LABEL COURSE="Docker" \
      DURATION="12Hours" \
      SOURCE="Amazon Web Services"