# FROM is used to mention the base OS of the image. It should be the first instruction in Dockerfile.
# Almalinux is exactly same as Redhat Image version 9
# ENTRYPOINT is used to provide the command executed by the container when it is started.
# We can override the command inside CMD instruction at run time.
FROM almalinux:9
# CMD ["ping","google.com"]
ENTRYPOINT ["ping","google.com"]