# FROM is used to mention the base OS of the image. It should be the first instruction in Dockerfile.
# Red Hat Universal Base Image 9
# RUN instruction is used to install packages or configure image.
FROM redhat/ubi9
RUN dnf install nginx -y