# FROM is used to mention the base OS of the image. It should be the first instruction in Dockerfile.
# Almalinux is exactly same as Redhat Image version 9
# ENV instruction sets the environment variable (key) to the value (value).
# ENV is used to provide env variables to the container. App code can access these env variables and use them.
FROM almalinux:9
ENV MONGO_URL="mongodb-dev.devopsdaws.online" \
    MONGO_URL="admin"